server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: tickITPro_API
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://byron-fedele-p0.cyrzpkhtkdab.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema=tickITPro
    username: postgres
    password: 4d2vAY9dzSGZsEy
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
# This is for our actuator
management:
  endpoints:
    web:
      exposure:
        includes:
          - "health"
          - "beans"
          - "info"